/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import javax.swing.JOptionPane;
import projetostream.ProjetoStream;

/**
 *
 * @author josel
 */
public class CadastraFamosos extends javax.swing.JFrame {
        private boolean escolha = false;
        private boolean escolhaAtor = false;
        private boolean ajuda = true;
    /**
     * Creates new form CadastraAtores
     */
    public CadastraFamosos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        comboEscolha = new javax.swing.JComboBox<>();
        labelEscolha = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelFuncao = new javax.swing.JLabel();
        txtFuncao = new javax.swing.JTextField();
        radMasculino = new javax.swing.JRadioButton();
        radFeminino = new javax.swing.JRadioButton();
        labelSexo = new javax.swing.JLabel();
        labelPersonagem = new javax.swing.JLabel();
        txtPersonagem = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPAjuda = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        comboEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "ATORES", "OUTROS" }));
        comboEscolha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEscolhaItemStateChanged(evt);
            }
        });
        comboEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEscolhaActionPerformed(evt);
            }
        });

        labelEscolha.setText("ESCOLHA:");

        labelNome.setText("NOME:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        labelFuncao.setText("FUNÇÃO:");

        buttonGroup1.add(radMasculino);
        radMasculino.setText("MASCULINO");

        buttonGroup1.add(radFeminino);
        radFeminino.setSelected(true);
        radFeminino.setText("FEMININO");

        labelSexo.setText("SEXO:");

        labelPersonagem.setText("NOME DO PERSONAGEM:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtPAjuda.setEditable(false);
        txtPAjuda.setContentType(""); // NOI18N
        txtPAjuda.setText("POR FAVOR ESCOLHA O QUE DESEJA CADASTRAR NAS ESCOLHAS ACIMA, ATORES OU OUTROS PARA OUTROS MEMBROS DE ELENCO");
        jScrollPane1.setViewportView(txtPAjuda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radFeminino)
                            .addComponent(radMasculino)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPersonagem)
                                .addGap(18, 18, 18)
                                .addComponent(txtPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEscolha)
                                    .addComponent(labelNome)
                                    .addComponent(labelFuncao)
                                    .addComponent(labelSexo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(comboEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelEscolha)
                        .addComponent(comboEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFuncao)
                    .addComponent(txtFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(labelSexo)
                .addGap(18, 18, 18)
                .addComponent(radMasculino)
                .addGap(18, 18, 18)
                .addComponent(radFeminino)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPersonagem)
                    .addComponent(txtPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.labelNome.setVisible(escolha);
        this.labelFuncao.setVisible(escolha);
        this.labelSexo.setVisible(escolha);
        this.labelPersonagem.setVisible(escolhaAtor);
        this.txtNome.setVisible(escolha);
        this.txtFuncao.setVisible(escolha);
        this.txtPersonagem.setVisible(escolhaAtor);
        this.radMasculino.setVisible(escolha);
        this.radFeminino.setVisible(escolha);
        this.jScrollPane1.setVisible(ajuda);
        
    }//GEN-LAST:event_formWindowOpened

    private void comboEscolhaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEscolhaItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_comboEscolhaItemStateChanged

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowStateChanged

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void comboEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEscolhaActionPerformed
        // TODO add your handling code here:
         if(this.comboEscolha.getSelectedItem().toString().equals("ATORES")){
            this.escolha = true;
            this.escolhaAtor = true;
            this.ajuda = false;
        }else if(this.comboEscolha.getSelectedItem().toString().equals("OUTROS")){
            this.escolha = true;
            this.escolhaAtor = false;
            this.ajuda = false;
        }else{
            this.escolha = false;
            this.escolhaAtor = false;
            this.ajuda = true;
        }
        this.labelNome.setVisible(escolha);
        this.labelFuncao.setVisible(escolha);
        this.labelSexo.setVisible(escolha);
        this.labelPersonagem.setVisible(escolhaAtor);
        this.txtNome.setVisible(escolha);
        this.txtFuncao.setVisible(escolha);
        this.txtPersonagem.setVisible(escolhaAtor);
        this.radMasculino.setVisible(escolha);
        this.radFeminino.setVisible(escolha);
        this.jScrollPane1.setVisible(ajuda);
        
    }//GEN-LAST:event_comboEscolhaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        ProjetoStream novo = new ProjetoStream();
        //COMEÇA CADEIA DE IF'S ------------------------------------------//
        
        if(comboEscolha.getSelectedItem().toString().equals("OUTROS")){
            
            if(radMasculino.isSelected()) novo.insereAstro(0, txtNome.getText(), txtFuncao.getText(), 'm', "");
            
            else if(radFeminino.isSelected()) novo.insereAstro(0, txtNome.getText(), txtFuncao.getText(), 'f', "");
            
            else JOptionPane.showMessageDialog(this, "SELECIONE PELO MENOS UM DOS DOIS,"
                    + " FEMININO OU MASCULINO CLICANDO EM UM DELES COM QUAL SE IDENTIFICA");
            
        //OUTRO ELSE IF -------------------------------------------//
        
        }else if(comboEscolha.getSelectedItem().toString().equals("ATORES")){
            
            if(radMasculino.isSelected()) novo.insereAstro(1, txtNome.getText(), txtFuncao.getText(), 'm', txtPersonagem.getText());
            
            else if(radFeminino.isSelected()) novo.insereAstro(1, txtNome.getText(), txtFuncao.getText(), 'f', txtPersonagem.getText());
            
            else JOptionPane.showMessageDialog(this, "SELECIONE PELO MENOS UM DOS DOIS,"
                    + " FEMININO OU MASCULINO CLICANDO EM UM DELES COM QUAL SE IDENTIFICA");
            
        //OUTRO ELSE ----------------------------------------------//
        
        }else JOptionPane.showMessageDialog(this, "FAÇA A ESCOLHA DO QUE GOSTARIA DE CADASTRAR, UMA ATOR"
                + "OU OUTRO MEMBRO DE ELENCO");
        
        //FECHA JANELA APOS CADASTRAR -------------------------------------------//
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraFamosos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraFamosos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraFamosos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraFamosos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraFamosos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboEscolha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEscolha;
    private javax.swing.JLabel labelFuncao;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPersonagem;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JRadioButton radFeminino;
    private javax.swing.JRadioButton radMasculino;
    private javax.swing.JTextField txtFuncao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextPane txtPAjuda;
    private javax.swing.JTextField txtPersonagem;
    // End of variables declaration//GEN-END:variables
}
